%% initialization
clear; close all; clc;
rest = 'D:\PINGPONG\DATA\12_BCH1_GST2_020425\setRest\Subj2';
task = 'D:\PINGPONG\DATA\12_BCH1_GST2_020425\setTask\Subj2';
path      = task; % replace with the path containing noisy files
rest_path = rest; % replace with the path containing rest files
save_path = 'D:\PINGPONG\DATA\12_BCH1_GST2_020425\setTaskClean\Subj2';
load([rest, '\covR.mat']) % this matrix is generated by embrace_01_covR_rest.m file
load([rest,'\eig_val_dist_clean_M.mat']) % this matrix is generated by embrace_02_eigavl_dist_permutation.m file

P               = prctile(mean(eigen_values,2),90); % replace 90 with a number between 0 and 100 to control the threshold value for the noisy components detection
window_length   = 256;  % in sample
overlap_percent = 0;    % in percent
amp_threshold   = 0;    % let the algorithm clean all segments to keep continuity (if you want to keep eeg segments with amplitude below X untouched, set amp_threshold = X)
reg_covR = squeeze(mean(covR,1));
%% SET files
set_files = dir(fullfile(path, '*.set'));
set_files_rest = dir(fullfile(rest_path, '*.set'));

%% loop over set files 
for data_ind = 1:numel(set_files)

    clc;

    fprintf(['WORKING ON EEG SET ' num2str(data_ind) ' / ' num2str(numel(set_files)) ' ...\n'])

    % covR of clean data
    % reg_covR = squeeze(covR(data_ind,:,:));
    
    % load data 
    data_name    = set_files(data_ind).name;
    EEG          = pop_loadset(data_name, [path '\']);
    EEG.setname  = 'main';
    ALLEEG       = EEG;
    CURRENTSET   = numel(ALLEEG);

    % extract the rest data
    data_name_rest         = set_files_rest(1).name;
    EEG                    = pop_loadset(data_name_rest, [rest_path '\']);
    rest_data = EEG.data;
    EEG.setname            = 'rest';
    ALLEEG(CURRENTSET + 1) = EEG;
    CURRENTSET             = numel(ALLEEG);

    % extract the noisy data
    % total_time             = ALLEEG(CURRENTSET-1).xmax;
    % start_time             = 360;              % remove the first 6 minutes
    % end_time               = total_time - 360; % remove the last 6 minutes
    % EEG                    = pop_select(ALLEEG(CURRENTSET-1), 'time', [start_time end_time]);
    EEG = ALLEEG(1);
    EEG.setname            = 'noisy';
    ALLEEG(CURRENTSET + 1) = EEG;
    CURRENTSET             = numel(ALLEEG);

    % finding bad channels
    [EEG, no_prdc_chan]    = embrace_func_handle_periodic_channels(ALLEEG(CURRENTSET));
    [EEG, no_rmvd_chan]    = embrace_func_handle_bad_channels(EEG);
    EEG.setname            = 'interpolated';
    ALLEEG(CURRENTSET + 1) = EEG;
    CURRENTSET             = numel(ALLEEG);
    
    % denoise by GED
    eeg                    = ALLEEG(CURRENTSET).data;
    [recon_eeg,num_components,eigvalues] = embrace_func_reconstruct_v2(eeg, reg_covR, window_length, overlap_percent, amp_threshold, P);
    EEG.data               = recon_eeg;
    EEG.setname            = 'ged';
    ALLEEG(CURRENTSET + 1) = EEG;
    CURRENTSET             = numel(ALLEEG);


    % for i = 1: size(recon_eeg,1)
    %     [ mspettro(i,:), f ] = itab_spectrum( recon_eeg(i, :), 128);
    %     [ mspettroR(i,:), f ] = itab_spectrum( rest_data(i, :), 128);
    % end
    % figure
    % subplot(211)
    % plot(recon_eeg')
    % subplot(212)
    % plot(eeg')
    % figure 
    % subplot(211)
    % plot(rest_data')
    % subplot(212)
    % plot(f, mspettroR')
    % subplot(211)
    % Centro i dati
    % X = recon_eeg';
    % X_centered = X - mean(X, 1);
    % 
    % % PCA
    % [~, ~, latent] = pca(X_centered);
    % threshold = 1e-6;
    % rango_pca = sum(latent > threshold);
    % pause

    % save the denoised data
    pop_saveset(ALLEEG(CURRENTSET),data_name,save_path);

    clear ALLEEG

    fprintf('------------------------------------- \n')
end
